# Generated by Django 4.2.4 on 2023-08-11 10:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='PCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(default='', max_length=30)),
                ('cpu', models.CharField(default='', max_length=30)),
                ('gpu', models.CharField(default='', max_length=40)),
                ('rom', models.CharField(default='', max_length=15)),
                ('ram', models.CharField(default='', max_length=15)),
                ('added_at', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('price', models.CharField(max_length=255)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_shop.categorymodel')),
            ],
            options={
                'db_table': 'pc_shop',
            },
        ),
    ]
