# Generated by Django 4.2.4 on 2023-08-08 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_name', models.CharField(default='', max_length=100)),
                ('Created_at', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('Done', models.BooleanField(default='False')),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
