# Generated by Django 4.2.3 on 2023-08-05 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default='', max_length=200)),
                ('added_at', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
