# Generated by Django 4.2.3 on 2023-08-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmodel',
            name='title',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
