# Generated by Django 4.2.4 on 2023-08-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subjectmodel_added_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmodel',
            name='added_at',
        ),
    ]
